#!/usr/bin/env bash
# =============================================================================
# get-variables.sh
# Auto-discovers cloud provider variables and generates terraform.tfvars
# Usage: ./scripts/get-variables.sh [dev|stg|prd]
# =============================================================================
set -euo pipefail

ENV=${1:-dev}
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo "=============================================="
echo "  Auto-discovering cloud variables for: $ENV"
echo "=============================================="
echo ""

# --- AWS ---
echo -e "${CYAN}--- AWS ---${NC}"
if command -v aws &>/dev/null && aws sts get-caller-identity &>/dev/null; then
  AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
  AWS_REGION=$(aws configure get region 2>/dev/null || echo "eu-west-1")
  AWS_USER_ARN=$(aws sts get-caller-identity --query Arn --output text)

  echo -e "${GREEN}Account ID:${NC}  $AWS_ACCOUNT_ID"
  echo -e "${GREEN}Region:${NC}      $AWS_REGION"
  echo -e "${GREEN}User/Role:${NC}   $AWS_USER_ARN"
else
  echo -e "${YELLOW}AWS CLI not authenticated. Run: aws configure${NC}"
  AWS_REGION="eu-west-1"
fi

# --- Azure ---
echo ""
echo -e "${CYAN}--- Azure ---${NC}"
if command -v az &>/dev/null && az account show &>/dev/null 2>&1; then
  AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
  AZURE_SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
  AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)
  AZURE_LOCATION="westeurope"

  echo -e "${GREEN}Subscription:${NC} $AZURE_SUBSCRIPTION_NAME ($AZURE_SUBSCRIPTION_ID)"
  echo -e "${GREEN}Tenant ID:${NC}    $AZURE_TENANT_ID"
  echo -e "${GREEN}Location:${NC}     $AZURE_LOCATION"
else
  echo -e "${YELLOW}Azure CLI not authenticated. Run: az login${NC}"
  AZURE_SUBSCRIPTION_ID="CHANGE_ME"
  AZURE_TENANT_ID="CHANGE_ME"
  AZURE_LOCATION="westeurope"
fi

# --- GCP ---
echo ""
echo -e "${CYAN}--- GCP ---${NC}"
if command -v gcloud &>/dev/null && gcloud auth application-default print-access-token &>/dev/null 2>&1; then
  GCP_PROJECT_ID=$(gcloud config get-value project 2>/dev/null || echo "CHANGE_ME")
  GCP_REGION=$(gcloud config get-value compute/region 2>/dev/null || echo "europe-west1")
  GCP_ACCOUNT=$(gcloud config get-value account 2>/dev/null || echo "unknown")

  echo -e "${GREEN}Project:${NC}  $GCP_PROJECT_ID"
  echo -e "${GREEN}Region:${NC}   $GCP_REGION"
  echo -e "${GREEN}Account:${NC}  $GCP_ACCOUNT"
else
  echo -e "${YELLOW}GCP CLI not authenticated. Run: gcloud auth application-default login${NC}"
  GCP_PROJECT_ID="CHANGE_ME"
  GCP_REGION="europe-west1"
fi

# --- Generate tfvars ---
TFVARS_FILE="environments/$ENV/terraform.tfvars"
echo ""
echo "=============================================="
echo -e "  Generating ${GREEN}$TFVARS_FILE${NC}"
echo "=============================================="

cat > "$TFVARS_FILE" << EOF
# Auto-generated by get-variables.sh on $(date -Iseconds)
# Review and adjust values before running terraform apply

project     = "hybrid-lz"
environment = "$ENV"

# AWS
aws_region = "$AWS_REGION"

# Azure
azure_subscription_id = "$AZURE_SUBSCRIPTION_ID"
azure_location        = "$AZURE_LOCATION"
azure_tenant_id       = "$AZURE_TENANT_ID"

# GCP
gcp_project_id = "$GCP_PROJECT_ID"
gcp_region     = "$GCP_REGION"

# Notifications
alarm_email = ""

# Cross-cloud VPN (set to true for stg/prd)
enable_cross_cloud_vpn = $([ "$ENV" = "prd" ] && echo "true" || echo "false")
EOF

echo ""
echo -e "${GREEN}Generated: $TFVARS_FILE${NC}"
echo -e "Review the file and update any ${YELLOW}CHANGE_ME${NC} values before applying."
echo ""
echo "Next steps:"
echo "  1. Review: cat $TFVARS_FILE"
echo "  2. Init:   cd environments/$ENV && terraform init"
echo "  3. Plan:   terraform plan -var-file=terraform.tfvars"
echo "  4. Apply:  terraform apply -var-file=terraform.tfvars"
